# This file contains my custom .bashrc additions. I have a script that sets it
# to be automatically imported into the system's .bashrc file in the home 
# directory. Wherever possible machine-specific items should be added to the 
# machine's .bashrc file, and general quality of life improvements (or items
# needed for many computers) should be added here.

# Jake's Custom Bits
alias zotero='./.zotero/install/zotero'source   
alias hi="echo hello"
alias Emma="echo The best person in the world"
alias emma="Emma"

# switch capslock and escape for vim purposes. 
/usr/bin/setxkbmap -option "caps:swapescape"



# function to activate realsese as a webcam that zoom can see. It takes as 
# it's first argument the camera number of the realsense's rgb feed.
# it's second argument is the video number of the loopback virtual device.
function realsense_zoom () {
local target=${2:-'video16'} 
local source=${1:-'video6'} 
sudo modprobe v4l2loopback video_nr=16
ffmpeg -hide_banner -f v4l2 -i /dev/${source} -vf format=yuv420p -f v4l2 /dev/${target}
}
